[package]
name = "rustic_io"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.56"
derive_more = "0.99.17"
scroll = "0.11.0"
scroll_derive = "0.11.0"

[dependencies.tokio]
version = "1.17.0"
features = ["full"]
